version: '2'
services:
    pf-app:
        image: pf
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pf-mysql:3306/pf?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pf-elasticsearch:9300
        ports:
            - 8080:8080
    pf-mysql:
        extends:
            file: mysql.yml
            service: pf-mysql
    pf-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pf-elasticsearch
